name: Ruan's blog
url: https://odendaal.uk
baseurl: ""
cdn: https://d3eeewfm2t14hd.cloudfront.net/blog/
plugins:
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

exclude_from_sitemap: true

# Exclude test posts from sitemap and RSS feeds
defaults:
  - scope:
      type: "pages"
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "posts"
      path: "_posts"
    values:
      sitemap: true
  - scope:
      type: "posts"
      path: "_posts"
    values:
      sitemap: false
    condition: "page.tags contains 'test'"
